apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  labels:
    app: node-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-dep
  template:
    metadata:
      labels:
        app: node-app-dep
    spec:
      containers:
      - name: node-app
        image: chetanhari/node-mysql:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "150Mi"
            cpu: "150m"
