apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  namespace: twotier
  labels:
    app: node-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-dep
  template:
    metadata:
      labels:
        app: node-app-dep
    spec:
      containers:
      - name: node-app
        image: chetanhari/node-mysql:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "150Mi"
            cpu: "150m"
        env:
        - name: DB_HOST
          value: "172.20.46.72"  # Change to MySQL service cluster IP or hostname for flexibility
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: DB_PORT
          value: "3306"  # Optional: hardcoded as MySQL default port

        # Attaching volume for storage
        volumeMounts:
        - name: persistent-storage
          mountPath: /app/data  # Adjust this path to where your app needs to store data

      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim  # Ensure this PVC exists
