apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  namespace: twotier
  labels:
    app: node-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-dep
  template:
    metadata:
      labels:
        app: node-app-dep
    spec:
      containers:
      - name: node-app
        image: chetanhari/node-mysql:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "150Mi"
            cpu: "150m"
        env:
        - name: DB_HOST
          value: "172.20.46.72"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQLDB_DOCKER_PORT
      